# Generated by Django 6.1.1 on 2026-09-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='et',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
